// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "HomePage": {
      "title": "Hello world!",
      "about": "Go to the about page"
    },
    "index": {
      "title": "Index!",
      "about": "About",
      "desc": "Index Desc"
    }
  };
export default messages;